### ISSUE TITLE
Fail to subscribe

### ISSUE THREAD

**Issue by themoken** [askedrelic/libgreader#9]
A basic test for subscribing to a new feed fails with the latest git:

``` python
#!/usr/bin/python2

from libgreader import GoogleReader, ClientAuthMethod, Feed

auth = ClientAuthMethod('whatever@gmail.com', 'password')

reader = GoogleReader(auth)

# Works
print '%s' % reader.getUserInfo()

# Doesn't Work
print '%s' % reader.subscribe("http://xkcd.com/atom.xml")
```

I actually found libgreader after my own homebrew experiment had the same 400 response, so perhaps the API has changed?

Anyway I get the following after the user info is printed:

```
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    print '%s' % reader.subscribe("http://xkcd.com/atom.xml")
  File "/home/jack/src/libgreader/libgreader/googlereader.py", line 200, in subscribe
    {'ac':'subscribe', 's': feedUrl})
  File "/home/jack/src/libgreader/libgreader/googlereader.py", line 252, in httpPost
    return self.auth.post(url, post_parameters)
  File "/home/jack/src/libgreader/libgreader/auth.py", line 96, in post
    r = urllib2.urlopen(req, data=postString)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by askedrelic** [comment]
Hey,

Without testing this, I think you need to have 'feed/' in front of the feed URL. You can see a test here https://github.com/askedrelic/libgreader/blob/master/tests/test_special_feeds.py#L51

I just added the subscribe/unsubscribe endpoints a few weeks ago, but I'm thinking about automatically adding/removing the 'feed/' component, it's just confusing.

**Comment by themoken** [comment]
Ahhh, yeah, that works. That is confusing. Thanks!
